name: Deploy

on: [push]

jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
          POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}

            steps:
                - name: Checkout code
                  uses: actions/checkout@v3

                - name: Setup Node.js
                  uses: actions/setup-node@v3
                  with:
                    node-version: "18"

                - name: Install dependencies
                  run: npm ci

                - name: Deploy
                  env:
                    POSTGRES_PRISMA_URL: ${{ secrets.POSTGRES_PRISMA_URL }}
                    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  run: |
                    npx prisma generate
                    npx sst deploy --stage prod
